### ISSUE TITLE
Trying to run it on php

### ISSUE THREAD

**Issue by jdsepulveda** [mesterj/RestFileUpload#1]
I'm checking the RestFileUpload, but I don't know exactly how can I read the information sent from Android to php server.

Could you help to know how can I read @PartMap Map<String, RequestBody> parameter in php?

Thanks in advance

**Comment by mesterj** [comment]
This is a retrofit 2.0 file upload test project. I am glad to help you. 
My server is wildfly with RestEasy (Java EE). I don't know how you can use with php. 
In the API interface there are many methods, clone the project and try new ways!
